name: Daily Workflow

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notebook

    - name: Run update_police_api_backfill notebook
      run: |
        jupyter nbconvert --to notebook --execute project/update_police_api_backfill.ipynb

    - name: Run feature_pipeline notebook
      run: |
        jupyter nbconvert --to notebook --execute project/feature_pipeline.ipynb

    - name: Run batch_inference notebook
      run: |
        jupyter nbconvert --to notebook --execute project/batch_inference.ipynb
