name: GitHub Pages Deploy

on:
  workflow_run:
    workflows: ["Daily Workflow"]
    types:
      - completed

jobs:
  deploy-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: GitHub Pages publish
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Page updated"
        commit_options: '--no-verify --signoff'

        # Use a single glob pattern to include all files and directories
        file_pattern: '**/*'

        repository: .

        status_options: '--untracked-files=no'

        skip_dirty_check: true

        skip_fetch: true

        skip_checkout: true

        push_options: '--force'

        # Ensure this points to the gh-pages branch explicitly
        branch: gh-pages
