name: GitHub Pages Deploy

on:
  workflow_run:
    workflows: ["Daily Workflow"]
    types:
      - completed
jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Images
        run: |
          # Your script for updating images here
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update images"
          git push
